#!/usr/bin/env python3
"""
generate_html_header.py — Converts stair.html to a gzipped PROGMEM C array
so the HTML is embedded directly in firmware.bin (no LittleFS upload needed).

Usage: python generate_html_header.py <input.html> <output.h>
"""
import sys
import gzip

def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <input.html> <output.h>")
        sys.exit(1)

    with open(sys.argv[1], 'rb') as f:
        raw = f.read()

    compressed = gzip.compress(raw, compresslevel=9)

    hex_values = ',\n  '.join(
        ', '.join(f'0x{b:02x}' for b in compressed[i:i+16])
        for i in range(0, len(compressed), 16)
    )

    header = f"""#pragma once
// ── Auto-generated by generate_html_header.py — do not edit ──
// Source:      html/stair.html
// Original:    {len(raw):,} bytes
// Compressed:  {len(compressed):,} bytes  (gzip -9, {100*len(compressed)//len(raw)}% of original)
#include <pgmspace.h>

const uint8_t STAIR_HTML_GZ[] PROGMEM = {{
  {hex_values}
}};
const uint16_t STAIR_HTML_GZ_LEN = {len(compressed)};
"""

    with open(sys.argv[2], 'w') as f:
        f.write(header)

    print(f"[html-gen] {sys.argv[1]} → {sys.argv[2]}")
    print(f"[html-gen] {len(raw):,} bytes → {len(compressed):,} bytes "
          f"(saved {len(raw)-len(compressed):,} bytes, "
          f"{100*(len(raw)-len(compressed))//len(raw)}% reduction)")

if __name__ == "__main__":
    main()
